name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        # Use the 'docker-container' driver to enable remote registry caching
        driver: docker-container

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    # The image build already installs Python dependencies. 

    - name: Set up Python for tests
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies for tests (CPU PyTorch)
      run: |
        # Use venv for clean testing environment, if desired
        pip install --upgrade pip
        pip install --no-cache-dir torch torchaudio --index-url https://download.pytorch.org/whl/cpu
        pip install --no-cache-dir -r requirements.txt

    - name: Run tests
      run: |
        # Note: Removed redundant 'source .venv/bin/activate' lines
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest tests

    # This step uses the full ghcr.io tag for pushing and caching
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:latest
        cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:latest,mode=max

    - name: Start SSH Agent and Load Key
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
        
    - name: Deploy to server via SSH
      run: |
        # Define necessary variables
        IMAGE_TAG="ghcr.io/${{ github.repository }}:latest"
        CONTAINER_NAME="zoominfo-stt"
        SERVER_USER="ubuntu"
        SERVER_IP="${{ secrets.SERVER_IP }}"
    
        # Execute deployment commands on the remote EC2 server
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
          echo "Starting Deployment..."
    
          # Pull the latest image using sudo
          sudo docker pull $IMAGE_TAG
    
          # Stop and remove the existing container (if running)
          sudo docker stop $CONTAINER_NAME 2>/dev/null || true
          sudo docker rm $CONTAINER_NAME 2>/dev/null || true
    
          # Deploy using the robust --network host configuration
          sudo docker run -d \
              --network host \
              --name $CONTAINER_NAME \
              -e HOST=0.0.0.0 \
              $IMAGE_TAG
    
          echo "Deployment complete. Check http://${SERVER_IP}:8000/health"
        EOF
            # Execute the script on the remote server using the loaded key
            ssh $SSH_OPTIONS $SERVER_USER@$SERVER_IP "$DEPLOY_SCRIPT"
          env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ github.actor }}
