name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Updated to v4 for best practice
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        # Use the 'docker-container' driver to enable remote registry caching
        driver: docker-container

    # --- 2. Login to Registry (Required for pushing/caching) ---
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    # --- 3. Optional: Run tests BEFORE build (Best Practice) ---
    # The image build already installs Python dependencies. 

    - name: Set up Python for tests (if needed)
      uses: actions/setup-python@v5 # Updated to v5 for best practice
      with:
        python-version: '3.12'

    - name: Install dependencies for tests (CPU PyTorch)
      run: |
        # Use venv for clean testing environment, if desired
        pip install --upgrade pip
        pip install --no-cache-dir torch torchaudio --index-url https://download.pytorch.org/whl/cpu
        pip install --no-cache-dir -r requirements.txt

    - name: Run tests
      run: |
        # Note: Removed redundant 'source .venv/bin/activate' lines
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest tests

    # --- 4. Build and Push Docker Image ---
    # This step uses the full ghcr.io tag for pushing and caching
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:latest
        cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:latest,mode=max

    # --- 5. Deploy to server via SSH (CRITICAL FIX: Use correct tag) ---
    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # Define the full image tag used by the build step
          IMAGE_TAG="ghcr.io/${{ github.repository }}:latest"
          CONTAINER_NAME="zoominfo-stt"

          # 1. Pull the image from the registry
          docker pull $IMAGE_TAG
          
          # 2. Stop and remove the old container
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true

          # 3. Run the new container, using the full image tag
          docker run -d -p 8000:8000 --name $CONTAINER_NAME $IMAGE_TAG